version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[transformers]]
name = "prettier"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"